---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by laowang.
--- DateTime: 2024/12/6 22:17
---

--- 异常次数加一
if redis.call('INCR', KEY[1]) == ARGV[3] + 1 then
    --- 异常次数超过预定值 加入节点到待下线节点
    redis.call('SADD', KEY[2], ARGV[1])
end

--- 刷新 key 超时时间
redis.call('EXPIRE', KEY[1], ARGV[2])