spring:
  application:
    name: oj_core
  config:
    import: 'nacos:'
  cloud:
    nacos:
      config:
        server-addr: aliyun:8848/oj_core-default.yaml
        namespace: 130ca8b2-25e2-4566-b013-da6005365e57
        group: support
        prefix: center
        file-extension: yaml
        username: nacos
        password: nacos
  profiles:
    active: default